### ISSUE TITLE
Jenkins URL 

### ISSUE THREAD

**Issue by raghu999** [jstabenow/jenkins-mesos#1]
Thank you for the Amazing project. We are trying to deploy the Jenkins-Master in Mesos . Jenkins URL needs to be static and deploying in Mesos will get a dynamic Jenkins URL this will cause a problem if we want to add the Private GITHUB OAUTH Authentication . Any Ideas/Suggestions we can come around this. We are not using Mesos-DNS for service discovery instead we Use Consul and Weave for networking.

**Comment by jstabenow** [comment]
Sorry for my latency ;-)

I have not enough knowledge about connecting Consul with Mesos. But you need a public reachable domain for Jenkins and this domain must be configured as "JENKINS_MESOS_JENKINSURL" too. I think the best way is to use a public running HAProxy (or similar) who is connected to Marathon. 

Maybe have a look at [DC/OS](https://github.com/mesosphere/dcos) and her [Universe](https://github.com/mesosphere/universe). And here is a Jenkins example: [CD-Demo](https://github.com/mesosphere/cd-demo)

Good luck
